#file: config.toml
prefix = "."
stop-words = "events/stopwords.txt"

dataset = "events"
corpus = "line.toml"
index = "idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[ranker]
method = "bm25"
